[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/portfolio"
  to = "/work/"
  status = 301
  force = true

[[redirects]]
  from = "/portfolio/*"
  to = "/work/:splat/"
  status = 301
  force = true
